### ISSUE TITLE
ReadProperties: atom 'avcC' is too small; overrun at property: configurationVersion (src/mp4atom.cpp,399)

### ISSUE THREAD

**Issue by huyutao3550346** [TechSmith/mp4v2#61]
hi, everyone. It happend a bug as the title When I use MP4Read interface in Mp4ToH264 function. 
here is my code.

```bash
MP4FileHandle oMp4File;
oMp4File = MP4Read(sMp4file);
if (!oMp4File)
{
    printf("Read error....%s\r\n",sMp4file);
    return -1;
}
```

and it's my mp4 file 
https://user-images.githubusercontent.com/29395068/145324955-0a748f4a-1a19-4357-a70f-59886802be5c.mp4

I use the mp4v2 lib version in 2.0.0 and run it in qnx. 

ffmpeg can convert this mp4 to H264 success when use command
```bash
ffmpeg -i test.mp4 -c:v libx264 test.h264
```
so I think the mp4 file is normal.

**Comment by enzo1982** [comment]
Hi, I looked through the issues here to see if I can find things to fix in my own MP4v2 fork.

I had a look at your video and can say it's indeed broken. The MP4 standard prescribes an AVC Configuration box (avcC) containing decoder configuration settings for H.264 files.

While your file contains the avcC box, it's entirely empty, i.e. contains no configuration data for the decoder. So MP4v2 is correct at rejecting it.

When I try to play the file or decode it with FFmpeg, I get only a grey image with some moving pixels. That's most likely not the intended output, but the result of decoding the video data using invalid decoder settings.

**Comment by StilgarISCA** [comment]
Closing based on prior conversation
